In [ ]:
import numpy as np
from numpy import linalg as LA
from scipy.linalg import lu

In [342]:
def ThomasAdelante(DP,DS,DI,b):
  """
    Resuelve un sistema tridiagonal de ecuaciones lineales Ax = b utilizando el algoritmo de Thomas
    con sustitución hacia adelante.

    Parámetros:
    -----------
    DP : array-like
        Vector de la diagonal principal de la matriz tridiagonal A. Tamaño n.
    DS : array-like
        Vector de la diagonal superior de la matriz tridiagonal A. Tamaño n-1.
    DI : array-like
        Vector de la diagonal inferior de la matriz tridiagonal A. Tamaño n-1.
    b : array-like
        Vector de términos independientes del sistema Ax = b. Tamaño n.

    Retorna:
    --------
    x : numpy array
        Vector solución del sistema Ax = b. Tamaño n.
    """
  # Tamaño de la matriz
  n = len(DP)
  # Se crea vector respecto al tamaño de la matriz
  x = np.zeros(n)
  
  for i in range(1, n):
      DP[i] = DP[i]-(DS[i-1]/DP[i-1])*DI[i-1]
  # Se calcula el primer elemento 
  x[0] = b[0]/DP[0]
  # Calculo de los elementos restantes
  for i in range(1, n):
      x[i] = (b[i]-DI[i-1]*x[i-1])/DP[i]
  return x



In [341]:
# Ejemplo de sustitucion hacia adelante
# Tamaño de la matriz
n = 5
# Crear la diagonal principal
DP=2*np.ones(n)
diagonal_principal = np.diag(DP)

# Crear la diagonal superior
DS=-np.ones(n-1)
diagonal_superior = np.diag(DS, k=1)

# Crear la diagonal inferior
DI=-np.ones(n-1)
diagonal_inferior = np.diag(DI, k=-1)

# Sumar las tres diagonales para obtener la matriz tribanda
matriz_tribanda = diagonal_principal + diagonal_superior + diagonal_inferior
print(matriz_tribanda)

# Vector resultado
b=np.ones(n)

[[ 2. -1.  0.  0.  0.]
 [-1.  2. -1.  0.  0.]
 [ 0. -1.  2. -1.  0.]
 [ 0.  0. -1.  2. -1.]
 [ 0.  0.  0. -1.  2.]]


In [343]:
ThomasAdelante(DP, DS, DI, b)


array([0.5, 1. , 1.5, 2. , 2.5])

In [344]:
# Solucion con Python
P, L, U = lu(matriz_tribanda)
LA.solve(L, b)

array([1. , 1.5, 2. , 2.5, 3. ])