In [33]:
import numpy as np

def norma_1(A):
    return np.max(np.sum(np.abs(A), axis=0))

# Ejemplo
A = np.array([[9, -6, 7],
              [-8, 7, -2],
              [7, -4, 1]])

norma = norma_1(A)
print("Matriz A:")
print(A)
print("Norma 1 de A:", norma)


Matriz A:
[[ 9 -6  7]
 [-8  7 -2]
 [ 7 -4  1]]
Norma 1 de A: 24
